name: wondercart
description: "Your go-to e-shopping app, brings the world of endless choices to your fingertips."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/icon/
    
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

